        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 27 17:15:40 2013
        MODULE DINITSUB_SETCI__genmod
          INTERFACE 
            SUBROUTINE DINITSUB_SETCI
            END SUBROUTINE DINITSUB_SETCI
          END INTERFACE 
        END MODULE DINITSUB_SETCI__genmod
