        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 27 17:15:40 2013
        MODULE INFOSUB_CI_REPORT__genmod
          INTERFACE 
            SUBROUTINE INFOSUB_CI_REPORT
            END SUBROUTINE INFOSUB_CI_REPORT
          END INTERFACE 
        END MODULE INFOSUB_CI_REPORT__genmod
